version: "2"
services:
  capi:
    container_name: capi
    image: surisoft/capi-gateway:1.0
    ports:
      - "8380:8380"
    environment:
      - api.gateway.api.running.inspector.period=60000
      - api.gateway.api.throttling.inspector.period=5000
      - api.gateway.grafana.create.panels=false
      - api.gateway.prometheus.endpoint=http://prometheus:9090
      - api.gateway.zipkin.endpoint=http://zipkin:9411/api/v2/spans
      - api.gateway.grafana.endpoint=http://localhost:8080/grafana
    links:
      - mongo
      - zipkin
  mongo:
    container_name: capi-mongo
    image: mongo
    ports:
      - "27017:27017"
  zipkin:
    container_name: capi-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  prometheus:
    container_name: capi-prometheus
    image: surisoft/prometheus:1.0
    ports:
      - "9090:9090"
    links:
      - capi
  grafana:
    container_name: capi-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - prometheus
  capi-rest:
    container_name: capi-rest
    image: surisoft/capi-gateway-rest:1.0
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongo
      - spring.data.mongodb.port=27017
    links:
      - mongo