version: "2"
services:
  capi:
    container_name: capi
    image: surisoft/capi-gateway:1.0
    ports:
      - "8380:8380"
    environment:
      - api.gateway.api.running.inspector.period=60000
      - api.gateway.api.throttling.inspector.period=5000
      - api.gateway.grafana.create.panels=false
      - api.gateway.prometheus.endpoint=http://prometheus:9090
      - api.gateway.zipkin.endpoint=http://zipkin:9411/api/v2/spans
      - api.gateway.grafana.endpoint=http://localhost:8080/grafana
      # Optional, uncomment if you want to enable HTTPS on your CAPI Server, if so, please read also the volumes section of this service.
      - server.ssl.enabled=true
      - server.ssl.key-store-type=PKCS12
      - server.ssl.key-store=/keys/capi.p12
      - server.ssl.key-store-password=capigateway
      - server.ssl.key-alias=capigateway
      - server.ssl.trust-store=/keys/truststore.jks
      - server.ssl.trust-store-password=capigateway
      - spring.data.mongodb.host=mongo
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.username=capi
      - spring.data.mongodb.password=capi
      - spring.data.mongodb.database=capi
    links:
      - mongo
      - zipkin
    volumes:
      # If you want to enable HTTPS, please map your local directory where you have the certificate for the CAPI spring boot application to be able to load it.
      # Also make sure that the server,ssl.key environment variables are not commented.
      - /home/coelhro/projects/keys:/keys
  mongo:
    container_name: capi-mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=capi
      - MONGO_INITDB_ROOT_USERNAME=capi
      - MONGO_INITDB_ROOT_PASSWORD=capi
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./mongo/db/:/data/db/
  zipkin:
    container_name: capi-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  prometheus:
    container_name: capi-prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    links:
      - capi
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    container_name: capi-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - prometheus
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml
  capi-rest:
    container_name: capi-rest
    image: surisoft/capi-gateway-rest:1.0
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongo
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.username=capi
      - spring.data.mongodb.password=capi
      - spring.data.mongodb.database=capi
      # Optional, uncomment if you want to enable HTTPS on your CAPI Server Rest, if so, please read also the volumes section of this service.
      - server.ssl.enabled=true
      - server.ssl.key-store-type=PKCS12
      - server.ssl.key-store=/keys/capi.p12
      - server.ssl.key-store-password=capigateway
      - server.ssl.key-alias=capigateway
      - server.ssl.trust-store=/keys/truststore.jks
      - server.ssl.trust-store-password=capigateway
    links:
      - mongo
    volumes:
      # If you want to enable HTTPS, please map your local directory where you have the certificate for the CAPI spring boot application to be able to load it.
      # Also make sure that the server,ssl.key environment variables are not commented.
      - /home/coelhro/projects/keys:/keys