name: CAPI-CICD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v6
      with:
        servers: '[{ "id": "github", "username": "rodrigoserracoelho", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
    - name: Build with Maven
      env:
        USENAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: mvn package --file pom.xml --settings ~/.m2/settings.xml
    - name: Set version
      run: echo ::set-env name=VERSION::$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
    - name: Docker Publish
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        name: surisoft/capi-gateway 
        tag: $VERSION
        username: surisoft 
        password: ${{ secrets.docker_secret }}
